### ISSUE TITLE
SmartWeatherIntentService - problem serializing [CurrentConditions] to JSON!

### ISSUE THREAD

**Issue by Marchuck** [trnql/trnql_interplay#1]
Hello, I've already setup TRNQL SDK for Android, but when I override method to get weather data:
protected void smartWeatherChange(WeatherEntry weather) { ... } 
I see error logs in console:
E/TRNQL_System﹕ !!! SmartWeatherIntentService - problem serializing [CurrentConditions] to JSON!
    java.lang.NullPointerException
            at com.trnql.smart.weather.SmartWeatherIntentService.a(Unknown Source)
            at com.trnql.smart.weather.SmartWeatherIntentService.a(Unknown Source)
            at com.trnql.smart.weather.SmartWeatherIntentService.a(Unknown Source)
            at com.trnql.smart.weather.a.ok_inBGT(Unknown Source)
            at com.trnql.rpcconnect.WebmethodsStub$NetCallback_weatherupdate.ok_inBGT(Unknown Source)
            at com.trnql.zen.rpcclient.e.a(Unknown Source)
            at com.trnql.zen.rpcclient.e.handleResponse(Unknown Source)
            at ch.boye.httpclientandroidlib.impl.client.AbstractHttpClient.execute(Unknown Source)
            at ch.boye.httpclientandroidlib.impl.client.AbstractHttpClient.execute(Unknown Source)
            at ch.boye.httpclientandroidlib.impl.client.AbstractHttpClient.execute(Unknown Source)
            at com.trnql.zen.rpcclient.NetClient.a(Unknown Source)
            at com.trnql.zen.rpcclient.NetClient.b(Unknown Source)
            at com.trnql.zen.rpcclient.d.run(Unknown Source)
            at com.trnql.zen.rpcclient.a.run(Unknown Source)
            at com.trnql.zen.rpcclient.NetClientWithoutExecutor.actuallyExecute(Unknown Source)
            at com.trnql.zen.rpcclient.NetClient.runRpcTask(Unknown Source)
            at com.trnql.rpcconnect.WebmethodsStub.weatherupdate(Unknown Source)
            at com.trnql.smart.weather.SmartWeatherIntentService.onHandleIntent(Unknown Source)
            at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by trnql** [comment]
Hi Marchuck

You can safely ignore this error (this is just an internal status message that shouldn't affect you in any way). Has this negatively impacted your app in any way? You can reach us directly at trusted-testers@trnql.com to get more timely support. 

Thanks
trnql eng team

**Comment by Marchuck** [comment]
Ok, I see problem appeared because in my country weather data is not easily reachable. Can I tell SDK which 'weather provider' should use? How can I make it more customize?

**Comment by trnql** [comment]
Currently, we don't have the ability to switch providers. Yes, the weather data availability varies by geography. We are planning to add more weather providers in the future to have overlap. We will keep you posted on when this is done.
